### ISSUE TITLE
not able to download dataset csida

### ISSUE THREAD

**Issue by nisarnabeel** [Zhang-xie/Wimuse#1]
Hi i live  in europe , i wanted to get access to csida dataset, however i m not used to baidu and stuff, could u provide alternatlively link, would be so kind for example to upload data on google drive or some other platform.

Thank you for making your codes public

**Comment by Zhang-xie** [comment]
Hi @nisarnabeel, sorry for the late reply. The CSIDA dataset has been uploaded to OneDrive: https://connecthkuhk-my.sharepoint.com/:u:/g/personal/zhangxie_connect_hku_hk/ESi7Py0PlcpPvbKLiH2JdN0BuFbZea0Qhutm20SOadyHWw?e=tndHts 
Please go and check it.
